### ISSUE TITLE
TODO Plan

### ISSUE THREAD

**Issue by Kucukaslan** [Kucukaslan/cs342_pj_01#1]
## Common Parts and Part A
- [x] client  submits the request  
 `histclient <intervalcount> <intervalwidth> <intervalstart>`
- [x] server execute and receive the client's request
- [x] server inform  childs about the interval etc. to
- [x] server creates message queue for child communication
- [x] create a child for each input file
- [x] child reads and prepare histogram data @MuhammedCanKucukaslan  @  https://github.com/MuhammedCanKucukaslan/cs342_pj_01_21901779/commit/f5c4331c01648dba6695d96784404467b8764aaa 
- [x] child sends data
- [x] parent receive/process the data taken from child
- [x] create cli->ser mq, and server->cli mq

## Part B
- [x] @GirayAkyol  implemented

## Part C
https://docs.google.com/document/d/1l_paRingkPF7U3nJEy8How61xMA2Z3KH9ldzEtaDf6I/edit?usp=sharing
- [x] #12
- [x] Compare the running time of child process usage and thread usage. 
- [x] Which one is faster. 
- [x] Plot some graphs. Do experiments and show results. Support your conclusions with your experimental results.
